export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Services } from "./Services";
export { default as Products } from "./Products";
export { default as Industries } from "./Industries";
export { default as WhyChooseUs } from "./WhyChooseUs";
export { default as Portfolio } from "./Portfolio";
export { default as Testimonials } from "./Testimonials";
export { default as Contact } from "./Contact";
